### ISSUE TITLE
Sort publications by number (for editors)

### ISSUE THREAD

**Issue by veronicar239** [pimbongaerts/mesophotic#10]
On Publications page, can we add a column (visible to editors only?) with the publication entry number (i.e. number automatically generated when new publication created) and the ability to sort publications numerically by publication number?

**Comment by pimbongaerts** [comment]
Implemented - also hard-coded number of publications per page as 95 (for editors), so that current list can be divided into 4 section to slit up for validations.

@ryanbooker - note, some small changes in Publications MVC: f16f17545f1c71d606d5246bfbeca365f8db329b
