### ISSUE TITLE
Credit for adding a publication

### ISSUE THREAD

**Issue by gonzaloprb** [pimbongaerts/mesophotic#100]
Hello Ryan, @ryanbooker 

With Pim we agreed that it would be good to add in the metadata section of a subpage publication the name of the person who added the manuscript and the metadata. 

Currently it only gives the information on Validated by: "Name" "Name"
It would be great if on top we can add : "Added By" : "Name" ; Validated by: "Name" "Name"

Thanks in advance
Gonzalo 

<img width="434" alt="Screenshot 2020-09-14 at 09 39 51" src="https://user-images.githubusercontent.com/52680141/93247778-18ff7400-f78f-11ea-97c5-3b1f212a391d.png">

**Comment by pimbongaerts** [comment]
@ryanbooker - would you be able to have a look at implementing this? Currently the associated "users" in Publications are the authors of each publication. But maybe we can introduce a separate field in Publications (e.g. "contributor_id"), and moving forward, link each publication to the user that added it? (We just have to make sure we catch all the current publications without a contributor_id in the view)

**Comment by ryanbooker** [comment]
Yeah. No problem. I somehow missed the initial question. :)

**Comment by gonzaloprb** [comment]
Hello Ryan, 

This was the initial question: 

One little question, do you think you may edit the information of the paper and add: “Publication added by: Name”; Validated by: “Name"

Perhaps this will encourage even more people on the team to add the publications because currently there is not credit of that action. If not possible or complicated, do not worry about it. 

Cheers, 
Gonzalo 



- - 
Gonzalo, PÉREZ-ROSALES
Ph.D. Candidate at CRIOBE - Laboratoire d’Excellence “CORAIL”
BP 1013, Papetoai, 98729 - MOOREA - POLYNESIE FRANÇAISE
gonzalo.prb@gmail.com
gonzalo.perez-rosales@ephe.psl.eu
Twitter: @Perez_Rosales_G
Tel: +689 87247772 / +34 687008652

**Comment by ryanbooker** [comment]
The user who creates a publication is now added as the "Contributor" and displayed with the Validating users.

**Comment by gonzaloprb** [comment]
Thank you Ryan and Pim,
Gonzalo
