### ISSUE TITLE
No pdf attachment

### ISSUE THREAD

**Issue by AIHAgreda** [pimbongaerts/mesophotic#103]
While creating a new record for book chapters (I don't think this happening for journal articles - I think), we're not able to attach pdfs. We can select the pdf and seems to be uploading, but after pressing 'Update publication', we're getting the error:

Pdf Paperclip::Errors::NotIdentifiedByImageMagickError

**Comment by pimbongaerts** [comment]
Would you mind having a look at this @ryanbooker ? They are trying to get these finished by the end of the year, but they have an issue with the PDF upload. @AIHAgreda - can you send @ryanbooker  an example of a PDF that fails to upload, so that he can repeat the error?

**Comment by ryanbooker** [comment]
ok

**Comment by AIHAgreda** [comment]
Sure. I just sent it an email with the example.

**Comment by ryanbooker** [comment]
Thanks!

**Comment by ryanbooker** [comment]
This appears to be imageMagic failing to create the PNG preview images from the PDF. However all the correct tools are still installed not eh server. ImageMagick and Ghostscript. 

@pimbongaerts Is there any kind path setup that needs to be fixed somewhere in the general Dreamhost setup? Maybe they reset something in those updates.

I also tried reinstalling gems, which has failed running out of space in /tmp, which means mesophotic is currently down. Only sudo users can delete from there, which I don’t think I am.

I need to run this:

`find /tmp -mtime +5 -exec rm -rf {} \;`


Then in mesonew

`bundle install`

**Comment by ryanbooker** [comment]
We're back up. Unfortunately reinstalling the gems didn't fix the issue.

**Comment by ryanbooker** [comment]
For now, I've disabled the preview generation for PDFs.  Which should allow you to upload them.

**Comment by pimbongaerts** [comment]
But won't that give us issues later? As we are using those previews across the website?
Maybe better to not upload PDFs until this is resolved?

**Comment by ryanbooker** [comment]
I can change it back if you want, I thought you said we need to get things uploaded before Xmas?

I have no idea why Rails can't find the Ghostscript stuff. It's all installed. The only thing that has changed in that regard is Dreamhost updating stuff. Are there paths that need to be set somewhere, or anything like that?

**Comment by pimbongaerts** [comment]
We need all the publications added yes, but ideally with all the previews too, as adding those later may be difficult with paperclip? Or do you think that could be straight-forward?

Attached the only setting that you can change.
![Screen Shot 2020-12-17 at 5 36 32 PM](https://user-images.githubusercontent.com/735720/102444602-78229c80-408e-11eb-9b3f-5c2d92c29c0c.png)

Would it be worth trying to change the PhP version to the recommended version?
![Screen Shot 2020-12-17 at 5 37 38 PM](https://user-images.githubusercontent.com/735720/102444680-a30cf080-408e-11eb-8ffd-91fb8033b5e6.png)

**Comment by ryanbooker** [comment]
I think we should log a ticket with them.

**Comment by ryanbooker** [comment]
I have no idea how hard it will be to generate them later. 

I also noticed that `Paperclip` is no longer in development. We're supposed to use `ActiveStorage` now. But that seems like a significant change with lots of database and data migrations. Not something to try to quickly push out.

**Comment by ryanbooker** [comment]
I have reenable the image generation.

**Comment by ryanbooker** [comment]
Ok. On my local machine over last night and today I have migrated from `Paperclip` to `ActiveStorage` for managing uploaded files. Everything seems to work fine and I've written myself a little migration plan/checklist to update the server. It will take several stages, and probably 30 min to 1 hr. I'll do it later on this evening.

After I've done the migration, PDF uploading will work. Previews of those PDFs may not initially work, but they will fix themselves in the future—I'm still trying to work out if the required dependency, `muPDF`, is installed on Dreamhost by default.

**Comment by ryanbooker** [comment]
Done. Everything seemed to update and work smoothly. Even PDF previews appear to be working.

**_Please let me know if anything is broken._**

**Comment by veronicar239** [comment]
@ryanbooker thanks for all this! However, I tried to edit a publication to upload the missing PDF but a general error occurs: "We're sorry, but something went wrong. If you are the application owner check the logs for more information." I also tried to get to the edit page of other random publications, and received the same error.

For reference, this is the publication I'm trying to edit:
http://mesophotic.org/publications/941/edit

**Comment by AIHAgreda** [comment]
@ryanbooker I'm getting the same error that @veronicar239 mentioned when trying to edit book chapters. See below:

![Screen Shot 2020-12-18 at 10 11 09 AM](https://user-images.githubusercontent.com/22438632/102646750-72be6400-4119-11eb-96db-8fcf78f46c23.png)

Here an example: http://mesophotic.org/publications/949/edit
