### ISSUE TITLE
Is Mesophotic.org down?

### ISSUE THREAD

**Issue by AIHAgreda** [pimbongaerts/mesophotic#106]
Hi @pimbongaerts and @ryanbooker - it looks like the page is down again
![Screen Shot 2021-01-20 at 9 01 01 AM](https://user-images.githubusercontent.com/22438632/105209639-e976c480-5afe-11eb-87f7-6c28d39a6517.png)

**Comment by ryanbooker** [comment]
Seems to be ok now…

**Comment by pimbongaerts** [comment]
I restarted the VPS. Not sure why it keeps happening though?

**Comment by ryanbooker** [comment]
Not sure. Seems like a questions for Dreamhost… I'll ask them. Is this the second time we've had to do that?

**Comment by pimbongaerts** [comment]
Sounds good! I think the third or fourth time.

**Comment by ryanbooker** [comment]
Ticket lodged

**Comment by ryanbooker** [comment]
They replied with basically: We can't see anything wrong, or any errors in settings. Let us know if it keeps happening.

**Comment by veronicar239** [comment]
Seems like some select pages such as the About page are down? But the Publications page and Photos page are working fine.

http://mesophotic.org/about

<img width="1157" alt="Screen Shot 2021-01-27 at 10 57 35 am" src="https://user-images.githubusercontent.com/25621305/106017515-8650d900-608e-11eb-9cf4-953ef39fa4ce.png">

**Comment by ryanbooker** [comment]
Ok. I've opened a separate issue (#107), and I'll look into it.

**Comment by ryanbooker** [comment]
FYI. I had to reboot the VPS again this afternoon. So I have logged another ticket.

**Comment by ryanbooker** [comment]
Dreamhost replied with some useful information. They said the site keeps hitting a memory limit. So we need to look into that… I've added "New Relic" monitoring. I've used it before on another site. It gives some useful metrics re memory usage and speed etc.

**Comment by pimbongaerts** [comment]
Site just went down again, so restarted VPS

**Comment by ryanbooker** [comment]
I've made several changes that I hope will reduce the memory footprint of several pages. Let's see… :)

**Comment by ryanbooker** [comment]
Problem seems mostly related to 
[]- publications#index csv generation
[]- summary#summary_keywords

**Comment by AIHAgreda** [comment]
Hi @ryanbooker and @pimbongaerts - it happened again 
<img width="653" alt="Screen Shot 2021-02-18 at 10 46 32 AM" src="https://user-images.githubusercontent.com/22438632/108406198-f1498780-71d6-11eb-9a0a-9fbdae0b8310.png">

**Comment by pimbongaerts** [comment]
VPS restarted. @ryanbooker - again related to memory footprint?

**Comment by ryanbooker** [comment]
I assume so. But I'm not sure what. It looks like it died just before midnight last night, and memory usage then seems to have been only around 300MB, well under the VPS memory, and I've spent the last week or more, reducing memory usage in some key places, and speeding several things up in the process…

I thought it was keywords/wordcloud generation as that was a hugely slow and memory inefficient process. I've already done a lot to speed that up, and have improved it significantly. I am also trying to work out how to move it into the DB, instead of Ruby, which should be a lot faster and more memory efficient.

I also wonder if the recent updates they did to the VPS have made an impact, because this problem is new.

We have also move to ActiveStorage for images recently, instead of Paperclip after that stopped working. So it could be related to that as well.

**Comment by pimbongaerts** [comment]
Thanks so much for looking into it Ryan!

**Comment by veronicar239** [comment]
Hi @ryanbooker , I just added 6 new photos and while they show on the Images page (http://www.mesophotic.org/photos) and in the specific Behind the Science post (http://www.mesophotic.org/posts/68), the individual photo pages show error messages. For example, http://www.mesophotic.org/photos/420 shows the error log message "We're sorry, but something went wrong." 

However, other (older) individual photo pages (such as, http://www.mesophotic.org/photos/419) open just fine.

**Comment by ryanbooker** [comment]
I think I've solved this memory issue, at least enough for the moment. Closing this issue. :)

**Comment by veronicar239** [comment]
Sorry to re-open this @ryanbooker but the same initial error message is showing again! 
 
<img width="558" alt="Screen Shot 2021-04-02 at 12 29 15 pm" src="https://user-images.githubusercontent.com/25621305/113434490-0fe29700-93af-11eb-8e70-8f3a22889617.png">

**Comment by pimbongaerts** [comment]
Just restarted VPS in the meantime
