### ISSUE TITLE
Image pages failing for new images

### ISSUE THREAD

**Issue by ryanbooker** [pimbongaerts/mesophotic#112]
Hi @ryanbooker , I just added 6 new photos and while they show on the Images page (http://www.mesophotic.org/photos) and in the specific Behind the Science post (http://www.mesophotic.org/posts/68), the individual photo pages show error messages. For example, http://www.mesophotic.org/photos/420 shows the error log message "We're sorry, but something went wrong." 

However, other (older) individual photo pages (such as, http://www.mesophotic.org/photos/419) open just fine.

_Originally posted by @veronicar239 in https://github.com/pimbongaerts/mesophotic/issues/106#issuecomment-798794575_

**Comment by ryanbooker** [comment]
@veronicar239 Thanks. I'll have a look.

**Comment by ryanbooker** [comment]
Fixed. :)

**Comment by veronicar239** [comment]
Awesome, thanks @ryanbooker !
