### ISSUE TITLE
server error - Phusion Passenger server

### ISSUE THREAD

**Issue by veronicar239** [pimbongaerts/mesophotic#114]
Hi @ryanbooker, not sure if this is a new issue or linked to the previous issues but the new mesophotic blog post I put up is not working: http://www.mesophotic.org/posts/68

The error message is:

<img width="569" alt="Screen Shot 2021-03-17 at 5 11 37 pm" src="https://user-images.githubusercontent.com/25621305/111539239-04069c00-8744-11eb-9543-a0280407ab38.png">

**Comment by pimbongaerts** [comment]
I restarted the VPS just as a quick fix - but not sure what's going on as server has been going down lots lately.

**Comment by ryanbooker** [comment]
It looks like the server stoped responding at about 0630. It doesn't _look_ like memory usage was super high at that time… but I'm not sure. I'll try to investigate later.

**Comment by pimbongaerts** [comment]
Over past 2 weeks, again several times it went down. Should we inquire with dreamhost?
In the meantime, @ryanbooker - would it maybe an idea to set up a cron job that sends us an email if the site is down?

**Comment by ryanbooker** [comment]
We can ask them again. I think they'll just say "memory". I will keep looking for more things.

I suspect image caching for species images.

Probably a good idea to set up some kind of notification.

**Comment by pimbongaerts** [comment]
OK - I have set up an email alert, so we can at least restart faster after going down.

**Comment by AIHAgreda** [comment]
Hi @pimbongaerts and @ryanbooker the server seems to be down again. See below
![Screen Shot 2021-05-26 at 2 36 31 PM](https://user-images.githubusercontent.com/22438632/119734456-e46cad80-be2f-11eb-86f4-aec7695ff758.png)

**Comment by ryanbooker** [comment]
Things seem relatively stable now.
