### ISSUE TITLE
Error: "Incomplete response received from application"

### ISSUE THREAD

**Issue by veronicar239** [pimbongaerts/mesophotic#115]
Hi @ryanbooker I'm not sure if this is related to other issues but I was trying to upload metadata for a new publication (http://www.mesophotic.org/publications/new) and it resulted in an error message "Incomplete response received from application"?

**Comment by ryanbooker** [comment]
Ok, thanks. I'll have a look.

**Comment by ryanbooker** [comment]
Hi @veronicar239 Have you seen this again? Did it eventually work for the publication you were trying to upload?

**Comment by veronicar239** [comment]
Hi @ryanbooker @pimbongaerts I just tried again and it worked! I just added one new publication but assuming it should work fine for all new publications. For reference, the new publication is http://www.mesophotic.org/publications/979/

**Comment by ryanbooker** [comment]
Great! I'll close this for now, but please let me know if it happens again. :)
