### ISSUE TITLE
Pooling duplicated locations together 

### ISSUE THREAD

**Issue by gonzaloprb** [pimbongaerts/mesophotic#150]
## ❕ Pool the duplicated locations of Italy together after deciding on keeping these two locations. 

Need an automatic change for #Italy - Ligurian-Tyrrhenian. This means forcing all locations #37 to #36

Need an automatic change for Italy - Adriatic-Ionian. This means forcing all locations #137 to #119

**Comment by ryanbooker** [comment]
Done.
