### ISSUE TITLE
Removing all associated records through checkboxes

### ISSUE THREAD

**Issue by pimbongaerts** [pimbongaerts/mesophotic#16]
The Publication edit page is not allowing you to delete all associations of a Publication to a particular model by unchecking all checkboxes in the form. For example: if you uncheck all locations or platforms from http://www.mesophotic.org/publications/38/edit - nothing changes when you "Update publication". If you make any changes (by adding or changing locations) - it works fine. Probably has something to do with no params being passed on when none of the checkboxes are checked, and therefore those changes are ignored. Seems like straight-forward issue, would you know how to solve this, @ryanbooker?

**Comment by ryanbooker** [comment]
Yeah. I can look into it. :)

**Comment by ryanbooker** [comment]
Fixed in #be069ba
