### ISSUE TITLE
Creative Commons option for photos

### ISSUE THREAD

**Issue by veronicar239** [pimbongaerts/mesophotic#17]
We discussed giving researchers the options to tick a box Y/N for Creative Commons licensing for the photos they share on the website. Could we add this option to the mesophotic.org/photos/new template page?

**Comment by pimbongaerts** [comment]
Also good to add an extra column indicating whether the photo should be included in the Location pages? (to avoid including more technical photos)

**Comment by pimbongaerts** [comment]
Creative Commons field now added (51bd156). Raised error with regards to [depreciated use](https://blog.bigbinary.com/2016/02/29/rails-5-improves-redirect_to_back-with-redirect-back.html) of `redirect_to :back` - so that update included in commit too.

**Comment by pimbongaerts** [comment]
Also added the column indicating whether the photo should be included in the Location pages (b7bbe9c)
