### ISSUE TITLE
Publications search / depth-range slider

### ISSUE THREAD

**Issue by pimbongaerts** [pimbongaerts/mesophotic#19]
Currently any search on the Publications page seems to return an Internal Server Error: `NoMethodError (undefined method `>=' for nil:NilClass)`. This error occurs when Searching without making any adjustments to the slider (Chrome). In Firefox the slider does not seem to show up - and so always results in the error.

**Comment by ryanbooker** [comment]
I've done a temporary fix for the crash. There is still a rendering issue on all browsers (which is what causes the crash). After clicking the link to "publications" in the navbar, the slider doesn't render. As soon as you refresh the page, either manually or by searching, the slider works again.

**Comment by ryanbooker** [comment]
This is fixed for now. Though I don't like the fix. I am still trying to find out why it's only needed for the initial load.
