### ISSUE TITLE
Retain two-part Author last name

### ISSUE THREAD

**Issue by veronicar239** [pimbongaerts/mesophotic#21]
In the publication author list, when a first author’s last name has two parts (e.g. van Oppen), the publication states “van” as the last name thus becomes van et al. 2011 (e.g. publication #103) but it is actually van Oppen et al. 2011. How do we get it to recognize that this is two parts (any word(s) preceding the initials)?

**Comment by ryanbooker** [comment]
Where do we get the name from in the first place? I would just drop initials, or the "first" name. Is there a convention in papers? There is probably a whole world of hidden complexity in identifying first/last names in different languages.

**Comment by pimbongaerts** [comment]
Fixed this (0f09e86) by splitting the first author string, and then taking all sections except for the last:

`first_author = first_author_full.split()[0..first_author_full.split().length-2].join(" ")`
