### ISSUE TITLE
Blog post error "Postable must exist"

### ISSUE THREAD

**Issue by veronicar239** [pimbongaerts/mesophotic#29]
@ryanbooker I'm having an issue adding a new blog post via http://www.mesophotic.org/admin/posts. The page to create a new post is working (I can enter the text) but when I click to Publish it is unable to publish the post quoting the error "Postable must exist".

**Comment by ryanbooker** [comment]
Ok. I’ll have a look. Thanks. :)

**Comment by ryanbooker** [comment]
Fixed. Marked portable as optional and fixed Markdown
