### ISSUE TITLE
word cloud slightly shifted onto text of blog post

### ISSUE THREAD

**Issue by veronicar239** [pimbongaerts/mesophotic#34]
I noticed that the word cloud has slightly shifted into the space of the text of the blog post. Depending how the word cloud assembles, it sometimes slightly overlaps with the text of the blog post. Here is a blog post for reference:

http://mesophotic.org/posts/tom-shlesinger

**Comment by ryanbooker** [comment]
Whoops. On it.

**Comment by ryanbooker** [comment]
Can you please link me to all the pages that show word clouds?

**Comment by ryanbooker** [comment]
Try now.
