### ISSUE TITLE
remove all numbers from word clouds

### ISSUE THREAD

**Issue by veronicar239** [pimbongaerts/mesophotic#35]
I noticed in a "research keywords" word cloud (on a personal profile page) that a lot of numbers are showing up. Since it's impossible to manually exclude all combinations of numbers, would it be possible to exclude any and all numbers from word clouds? See file attached for example of issue

<img width="395" alt="screen shot 2018-03-14 at 11 37 32 am" src="https://user-images.githubusercontent.com/25621305/37378785-7041a8c2-277c-11e8-8e21-60143cfaba89.png">

**Comment by ryanbooker** [comment]
Fixed.
