### ISSUE TITLE
Background image behind map no longer showing

### ISSUE THREAD

**Issue by pimbongaerts** [pimbongaerts/mesophotic#45]
The greyscale photo behind the map on the home page is not showing. Does not seem to get precompiled to asset folder: `http://mesophotic.org/assets/home_background_grey2.jpg`. Have tried to redo the precompile but does not help.. any ideas?

**Comment by ryanbooker** [comment]
Not sure. I’ll have a look. :)

**Comment by ryanbooker** [comment]
Fixed. Rails 5 asset helper urls are needed for css. Instead of url('home_background.jpg') it's image-url("home_background.jpg"). I also cleaned up a bunch of old unused images.

**Comment by ryanbooker** [comment]
There seems to be an `public.old` directory on the server in `misonew` that can probably just be deleted.
