### ISSUE TITLE
Page breaks if there is no contents for wordcloud

### ISSUE THREAD

**Issue by pimbongaerts** [pimbongaerts/mesophotic#47]
Wordcloud in member pages seems to break (`undefined method `last' for nil:NilClass`) if none of the linked publications have their full text indexed. For example: mesophotic.org/members/237

**Comment by ryanbooker** [comment]
Do you have a current example of a page that gets this error, so I can see the trace?

**Comment by ryanbooker** [comment]
I may have fixed this… But I don't have an example to test against. :)
