### ISSUE TITLE
Missing div?

### ISSUE THREAD

**Issue by pimbongaerts** [pimbongaerts/mesophotic#48]
Post page seems to render strangely? e.g. [this one](http://mesophotic.org/posts/early-life-history-traits-and-reproductive-ecology-of-brooding-coral-across-depth-gradient). Seems like missing div or something like that?

Maybe because of my latest merge? there were two conflicts with `application.css` and the `wordcloud.html.erb`

**Comment by ryanbooker** [comment]
Fixed.
