### ISSUE TITLE
Keyword highlighting/classification

### ISSUE THREAD

**Issue by pimbongaerts** [pimbongaerts/mesophotic#52]
- [x] Add species key word highlighting
- [x] Add species key word italicising
- [x] Add Species >-< Publication relation
- [x] Ignore short description unless long description appears as well
- [x] Also highlight shortened species name in abstracts/wordclouds (e.g. A. lamarcki)

Extend the keyword-highlighting beyond the short_description fields of the `Platform`, `Field`, `Location`, and `Focusgroup` models, to also include the `Species` model.

Note that species consist of two words, and that it should query both, as well as the shortened `#{first_word_genus[0,1]}. #{second_word_species}` (e.g. "Agaricia lamarcki" and "A. lamarcki"). However, ideally it would ignore matches that only have shortened version, as there can be duplicates there (e.g. Leptoseris scabra and Lithophyllon scabra both will be L. scabra), so it would need at least one full mention of the species. But may be tricky/slow? Let's discuss...

**Comment by ryanbooker** [comment]
I'm not clear on what the Speciation job is for? Species highlighting is working…

**Comment by pimbongaerts** [comment]
I think it refers to the description below - a job where we query the occurrence of each Species in the full text of all the publication, so all those associations are buffered (rather than queried every single time). The other remaining addition would be the Keywords table, that would work in a similar fashion.

**Comment by pimbongaerts** [comment]
Also - not sure whether we implemented the search for shortened species names (see last paragraph of original post)?

**Comment by ryanbooker** [comment]
Ah cool. I'll double check that as well.

**Comment by pimbongaerts** [comment]
I have updated the issue description and removed the new keyword feature (that we had not yet started on). So I think what remains is just the highlighting of species in the format "A. lamarcki".

**Comment by ryanbooker** [comment]
Did we want to do the "SpeciationJob" still? There is some gem stuff I've added for it at some point, but I haven't done the actual job yet… It would probably give some speed up, as currently we search for all species in all publications. Rather than just those that are valid for this specific publication.

**Comment by ryanbooker** [comment]
https://github.com/pimbongaerts/mesophotic/pull/74

**Comment by pimbongaerts** [comment]
I think we would use it, as it would then also allow us to easily list the number of publications for each species in the "Species page" (currently not working)? But not sure how much work it would be? Looks like you've already started setting up the link between species<->publications?

**Comment by ryanbooker** [comment]
Yeah. The plumbing is all there. I have haven't added the SpeciationJob (I have it on a branch). I'll set it up next. :)

**Comment by pimbongaerts** [comment]
Awesome!

**Comment by ryanbooker** [comment]
https://github.com/pimbongaerts/mesophotic/pull/82
