### ISSUE TITLE
Archived list of blog posts

### ISSUE THREAD

**Issue by veronicar239** [pimbongaerts/mesophotic#54]
Hi @ryanbooker would you be able to please help make an index of blog posts on the News page? Currently on the News page (http://mesophotic.org/posts), you can only see recent blog posts and it is not possible to find older posts. Would you be able to make a multi-page archive of blog posts, with the most recent posts listed at the top of the main News page? I imagine the current number of blog posts will go onto at least 2-3 pages (around 40 or so posts at the moment). Thanks!

**Comment by ryanbooker** [comment]
Yep! :) I have a hald a species feature too, that I need to finish. :)

**Comment by pimbongaerts** [comment]
I think all we'd need to do is add "pagination"?

**Comment by ryanbooker** [comment]
So just add pagination to the main news page? Or a new separate Archive page?

**Comment by pimbongaerts** [comment]
Yes - I think that's all that is needed.

**Comment by ryanbooker** [comment]
done.
