### ISSUE TITLE
Deploy latest

### ISSUE THREAD

**Issue by ryanbooker** [pimbongaerts/mesophotic#57]
I update to Rails 5.2 and tried deploying. Phusion Passenger couldn't start the app, so I rolled back by checking out the previous deployed commit. I thought you might have a better idea about Phusion Passenger.

To deploy we need to:
1. `git checkout master`
2. `bundle exec rails db:migrate`
3. restart the server (this fails and I didn't want to leave it dead while I tried to work out why).

**Comment by pimbongaerts** [comment]
Had a look too - but also could not figure it out. Had a look in the Dreamhost Panel too, but the only Passenger setting you can adjust is the path of RVM (`/home/mesophotic/.rvm/wrappers/ruby-2.5.0/ruby`), which is still current and correct. So also rolled back for now - and maybe wait with upgrade for a while?

**Comment by ryanbooker** [comment]
Yeah maybe? When is a good time window to look at it? i.e. a good time for the site to be down? :\

**Comment by pimbongaerts** [comment]
I think currently any time is fine - as long as we roll it back when we cannot figure it out. Looked at it for a while, but just could not find any leads to go on.

**Comment by ryanbooker** [comment]
OK. I might look a bit future later. How do I look at the Dreamhost Panel? Is that something you're ok with me checking?

**Comment by ryanbooker** [comment]
I've set the DreamHost RVM Ruby version to `/home/mesophotic/.rvm/wrappers/default/ruby` this way whatever we set on the command line as the default ruby is what will be used. No more need to edit DreamHost settings. Feel free to change the password back. :)

**Comment by ryanbooker** [comment]
This fixes the underlying Ruby version issue. But I still can't get the server to restart with Rails 5.2. So we're still in a rollback branch. :) I'll keep looking as I have time.

**Comment by ryanbooker** [comment]
I thought I logged a ticket, but I can't see it. So maybe I didn't.

**Comment by ryanbooker** [comment]
Just to make thing clear, in case you have a look as well. I have created a branch called `rollback` that is the latest Rails 5.1.6 and updated gems. So you can always easily switch back to that branch and restart. So it _seems_ that it's Rails 5.2 related. I might try the update again, from the rollback branch and see how that goes. Maybe I just did something wrong and accidentally overrode a setting somewhere.

**Comment by ryanbooker** [comment]
@pimbongaerts Fixed. The credentials system changed. I have updated the project to use the new encrypted credentials system.

**Comment by pimbongaerts** [comment]
Great that you managed to find out. Home page currently breaking with error though?
