### ISSUE TITLE
Metadata summary per page rather than search result

### ISSUE THREAD

**Issue by pimbongaerts** [pimbongaerts/mesophotic#60]
When selecting a specific field on the `fields` pages - it summarizes the result by paginated page rather than overall search result

**Comment by ryanbooker** [comment]
This is probably the same anywhere that summaries are done because the collection will be the subset for display on that particular page…

**Comment by ryanbooker** [comment]
Fixing this slows things down drastically. Fixing the Publication summary doesn't make much difference. Fixing the authors slows it down significantly, and fixing the word cloud slows it down to a crawl.

**Comment by ryanbooker** [comment]
For now I've just fixed the Publication Summary.

**Comment by ryanbooker** [comment]
I will look at rendering those summary boxes async, so they can do their calculations without holding up the entire page. Perhaps they can be cached somehow.

**Comment by pimbongaerts** [comment]
Awesome. For the time being maybe we can just set a max. number of publications for which authors and word cloud will be shown/rendered?

**Comment by ryanbooker** [comment]
https://github.com/pimbongaerts/mesophotic/pull/76
