### ISSUE TITLE
Blog post not showing on posts page

### ISSUE THREAD

**Issue by veronicar239** [pimbongaerts/mesophotic#61]
@ryanbooker 
The new Behind the Science post (http://www.mesophotic.org/posts/43 added on 28-3-19) is not showing on the main page http://mesophotic.org/posts. Further, the post is not showing on any of the three pages of archived BTS posts (I checked using control/find to look for the author's last name).

- [ ] new posts should automatically be added to the top of the 'posts' page
- [ ] all archived posts are stored within the multiple pages of mesophotic.org/posts

**Comment by ryanbooker** [comment]
This is because something is still saving bool columns as 't' and 'f'. When they're supposed to be '1' and '0' now. :\

**Comment by ryanbooker** [comment]
https://github.com/pimbongaerts/mesophotic/pull/64
