### ISSUE TITLE
Upload most recent species lists for coral and fish

### ISSUE THREAD

**Issue by pimbongaerts** [pimbongaerts/mesophotic#66]

**Comment by veronicar239** [comment]
Some species pages are working (e.g. http://mesophotic.org/species/30) but others are not (e.g. http://mesophotic.org/species/180)

**Comment by pimbongaerts** [comment]
OK - I have updated the species `table` with the most recent species lists (now >1,500 entries).

- [ ] @ryanbooker - would you mind refreshing the species<->publications associations?

- [ ] @ryanbooker - would you know how to mention the total publications count for each species on the species index page? I have included a placeholder: `<span class="badge"><%# species.publications.count TODO %></span>`.

- [ ] @ryanbooker - And if it's not too complicated, would it be possible to make the scraped images on the right of the show page async / load separately, as they are really slowing down the page loads?

**Comment by ryanbooker** [comment]
Ok. Haven't had a chance to do much of anything this week. :\

**Comment by pimbongaerts** [comment]
JK

**Comment by ryanbooker** [comment]
https://github.com/pimbongaerts/mesophotic/pull/82
