### ISSUE TITLE
Downloadable CSV for pages

### ISSUE THREAD

**Issue by pimbongaerts** [pimbongaerts/mesophotic#70]
Would be great if any of the pages showing the results of a simple publications query (listed below) provided a predictable link to download a CSV with the data. That would provide an easy way to download a relevant bibliography, or to run stats on those results directly from R. A link could be placed in the pagination sections, e.g.: ` 1 2 3 4 5 … Next › Last » [792 results] Download as csv `

- [x] `http://mesophotic.org/publications.csv` (already implemented, but link not yet there)
- [x] `http://mesophotic.org/locations/[id].csv`
- [x] `http://mesophotic.org/platforms/[id].csv`
- [x] `http://mesophotic.org/fields/[id].csv`
- [x] `http://mesophotic.org/focusgroups/[id].csv`
- [x] `http://mesophotic.org/species/[id].csv`

Also be great if the Publications > Search results were downloadable as CSV. That would provide a way to create very specific stats from a query. The CSV should not have the snippets from full text, but ideally with the dynamic 'occurrences' column - and in contrast to the regular page with search results it should also include publications with 0 occurrences. That way people can use the results to plot the occurrence of particular search terms over time (in a specific subset of literature, if only certain locations, categories, etc. are chosen).

- [x] `http://mesophotic.org/publications` (search)

**Comment by ryanbooker** [comment]
https://github.com/pimbongaerts/mesophotic/pull/75

**Comment by pimbongaerts** [comment]
@ryanbooker could you check - the output of this seems to be capped at 10 publications? Also, publications.csv currently raising an error.

**Comment by ryanbooker** [comment]
Ok. I'm sure that was all working! :D

**Comment by ryanbooker** [comment]
Fixed.

**Comment by pimbongaerts** [comment]
Would it actually be possible to give this one priority? Just as Veronica is hoping to redo these stats asap?

**Comment by ryanbooker** [comment]
https://github.com/pimbongaerts/mesophotic/pull/84
