### ISSUE TITLE
Stats page slow

### ISSUE THREAD

**Issue by pimbongaerts** [pimbongaerts/mesophotic#71]
The Stats page is extremely slow as it executes lots of individual queries (many of which are pretty inefficiently written). However, rather than rewriting the whole lot - could we have a message appear (along the lines of "Please hold while stats are being calculated...") before the rest of the page loads?

**Comment by ryanbooker** [comment]
https://github.com/pimbongaerts/mesophotic/pull/77

**Comment by pimbongaerts** [comment]
This works great btw!
