### ISSUE TITLE
[Stats page] Time series through 2018

### ISSUE THREAD

**Issue by veronicar239** [pimbongaerts/mesophotic#78]
On the Stats page, the "Use of term mesophotic" graph and "potential refuge role" graph both show data through 2017 only. For consistency with other figures, could you update this so the data includes 2018? (I'll need to download the updated csv file for the time series figure for the paper)

@pimbongaerts

**Comment by pimbongaerts** [comment]
Changed it to always show until one year prior to the current year (`last_year = Time.now.year - 1`) 334d17a
