### ISSUE TITLE
Locations page currently breaks

### ISSUE THREAD

**Issue by pimbongaerts** [pimbongaerts/mesophotic#81]
http://mesophotic.org/locations
`undefined method `original' for nil:NilClass`
` <% if @publications.original.present? %>`

Was this a scope that inadvertently got deleted?

**Comment by ryanbooker** [comment]
The error means `@publications` is nil. I will have to have a look.

**Comment by ryanbooker** [comment]
Which location is breaking? I just picked one at random "32" and it worked. So I guess there is a location with no publications. That should be easy to handle. :)

**Comment by pimbongaerts** [comment]
the index page itself: http://mesophotic.org/locations

**Comment by ryanbooker** [comment]
Fixed.

**Comment by pimbongaerts** [comment]
awesome!
