### ISSUE TITLE
Ensure Species names aren't singularised

### ISSUE THREAD

**Issue by ryanbooker** [pimbongaerts/mesophotic#83]
- [ ] The singularization in word clouds gives many weird outcomes (Agaricium for the genus Agaricia, Madraci for the genus Madracis) - probably need to disable this and accept that we will have multiple entries in the word cloud?

**Comment by ryanbooker** [comment]
Is there a way to get a master list of the words we don't want singularised? Do they just come from the species names?

**Comment by pimbongaerts** [comment]
Yes - just from species names!
