### ISSUE TITLE
Stats page

### ISSUE THREAD

**Issue by pimbongaerts** [pimbongaerts/mesophotic#85]
The `include_in_stats` scope from `publications.rb` should only consider `validated` publications, but that criterion was missing from the scope. I have now added the `validated` scope inside the `include_in_stats` scope, but it does not seem to affect the number of publications considered on the stats page? (734 instead of 689) @ryanbooker - would you mind having a look at that?

Similarly, in the `stats_controller.rb`, the `summarized_journals`, `summarized_focusgroups`, etc. (for the top 10 graphs) are done with a join on the overall `Publication` model - but these should be calculated from only publications that meet the `included_in_stats` scope. Veronica also suggested that we should calculate these as percentages of overall associations (e.g. count of "Great Barrier Reef" associations / count of all location associations)?

**Comment by ryanbooker** [comment]
Ok. I'll have a look.

**Comment by ryanbooker** [comment]
[ ] - Include_in_stats should only return validated results
[ ] - Summarised_journals, summarised_focusgroups etc, should only use validated results (as above)
[ ] - Express stats as %, e.g. GBR count / All locations count

**Comment by ryanbooker** [comment]
This is quite difficult. I think it will take a fair amount of refactoring the scopes etc. The big scopes list `included_in_stats` and `relevance` don't play well together. They conflict with each other and you get back incorrect results (if any).

**Comment by ryanbooker** [comment]
I just stayed up and did this. So all the stats *should* be using the correct set of publications now.

**Comment by ryanbooker** [comment]
As far as I can tell the percentages are already expressed as a percentage of the category total.
