### ISSUE TITLE
Species page

### ISSUE THREAD

**Issue by pimbongaerts** [pimbongaerts/mesophotic#87]
Reviewer reports that when clicking on a specific species that they get an error message. However, have not yet been able to reproduce - need to look into further.

**Comment by ryanbooker** [comment]
ok. Do we know the specific species?

**Comment by pimbongaerts** [comment]
Unfortunately not. I tried a whole lot of them, but they all worked okay.

**Comment by ryanbooker** [comment]
Closing. It will pop up again, if we find the issue. :)
