### ISSUE TITLE
New/merged Focus group "Symbiodiniaceae"

### ISSUE THREAD

**Issue by veronicar239** [pimbongaerts/mesophotic#97]
Should we edit the current Focus group "Symbiodinium" (focus group #4) to include "Symbiodiniaceae"? Or make a merged focus group "Symbiodiniaceae" that picks up the keywords "Symbiodiniaceae" and "Symbiodinium"? At present, "Symbiodinium" is picked as focus group #4 but newer publications using the family name "Symbiodiniaceae" and potentially looking at non-Symbiodinium genera would not be picked up.

Example- Ryan Eckert's new paper:  http://mesophotic.org/publications/842

**Comment by pimbongaerts** [comment]
Have to consult @ryanbooker here - as he created the keyword links in abstracts and wordclouds: does it split the strings in 'Short description' and searches those separately? If so, would it just be a matter of adding this extra keyword?

**Comment by ryanbooker** [comment]
I can't remember. But I'll have a look. :)

**Comment by ryanbooker** [comment]
Done. :)
